using Abo.Contracts.Models;
using Abo.Core.Connectors;
using Abo.Integrations.GitHub;
using Microsoft.Extensions.Configuration;
using System.Text.Json;

namespace Abo.Tests;

public class GitHubIssueTrackerConnectorIntegrationTests
{
    private readonly GitHubIssueTrackerConnector _connector;

    public GitHubIssueTrackerConnectorIntegrationTests()
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(Path.GetFullPath(@"..\..\..\..\Abo.Pm"))
            .AddJsonFile("appsettings.json", optional: false)
            .AddJsonFile("appsettings.Development.json", optional: true)
            .AddUserSecrets("2382c563-3cdf-48a5-a819-7cc76d5a465c")
            .AddEnvironmentVariables()
            .Build();

        var token = config["Integrations:GitHub:Token"];
        Assert.False(string.IsNullOrWhiteSpace(token), "GitHub token was not found in AppSettings or UserSecrets.");

        var envFile = Path.Combine(Path.GetFullPath(@"..\..\..\..\Abo.Pm"), "Data", "Environments", "environments.json");
        var envJson = File.ReadAllText(envFile);
        var envs = JsonSerializer.Deserialize<List<ConnectorEnvironment>>(envJson, new JsonSerializerOptions { PropertyNameCaseInsensitive = true }) ?? new();
        var githubEnv = envs.First(e => e.IssueTracker != null && e.IssueTracker.Type.Equals("github", StringComparison.OrdinalIgnoreCase));

        _connector = new GitHubIssueTrackerConnector(githubEnv.IssueTracker!, token, githubEnv.Name);
    }

    [Fact]
    public async Task E2E_IssueLifecycle_Create_UpdateProjectStatus_Delete()
    {
        // 1. Create an Issue
        var testTitle = $"INT-TEST-AUTO: {Guid.NewGuid().ToString().Substring(0, 8)}";
        var createdIssue = await _connector.CreateIssueAsync(
            title: testTitle,
            body: "This is a temporary issue generated by automated integration tests.",
            type: "task",
            size: "1",
            project: "" // Empty project avoids Bot Triage hijacking!
        );

        Assert.NotNull(createdIssue);
        Assert.False(string.IsNullOrWhiteSpace(createdIssue.Id));
        Assert.False(string.IsNullOrWhiteSpace(createdIssue.NodeId));
        
        try
        {
            // 2. Refresh issue to verify Creation project bindings
            var refreshed = await _connector.GetIssueAsync(createdIssue.Id);
            Assert.NotNull(refreshed);
            // CreateIssueAsync prepends "[abo] " to the title before sending to GitHub
            Assert.Equal($"[abo] {testTitle}", refreshed.Title);
            
            // Allow a tiny delay because GitHub Projects V2 GraphQL indexes asynchronously sometimes.
            await Task.Delay(2000);

            // 3. Chain 1: Move to 'open'
            await _connector.UpdateIssueAsync(createdIssue.Id, project: "requested", stepId: "open");
            await Task.Delay(2000);
            var verify1 = await _connector.GetIssueAsync(createdIssue.Id);
            Assert.NotNull(verify1);
            if (!string.IsNullOrWhiteSpace(verify1.Project)) {
                Assert.Equal("requested", verify1.Project);
            }

            // 4. Chain 2: Evict from project (Simulating a dropped linkage entirely)
            await _connector.UpdateIssueAsync(createdIssue.Id, project: "");
            await Task.Delay(2000);
            var verify2 = await _connector.GetIssueAsync(createdIssue.Id);
            Assert.NotNull(verify2);
            // When explicitly removed, it shouldn't contain any natively tracked tracking states
            Assert.True(string.IsNullOrWhiteSpace(verify2.Project), $"Project was expected empty on Chain 2, got {verify2.Project}");

            // 5. Chain 3: Restore to 'open'
            await _connector.UpdateIssueAsync(createdIssue.Id, project: "requested", stepId: "open");
            await Task.Delay(2000);
            var verify3 = await _connector.GetIssueAsync(createdIssue.Id);
            Assert.NotNull(verify3);
            
            // The connector reads the raw board status field — StepId reflects what was set via the stepId parameter.
            // GetIssueAsync returns the actual board value ("open"), not a fallback-resolved value.
            if (!string.IsNullOrWhiteSpace(verify3.Project)) {
                Assert.Equal("requested", verify3.Project);
                Assert.Equal("open", verify3.StepId);   // "open" was explicitly set via stepId on UpdateIssueAsync
            }
        }
        finally
        {
            // 5. Delete Issue securely in the finally block regardless of test assertion success
            if (!string.IsNullOrWhiteSpace(createdIssue.Id))
            {
                var deleted = await _connector.DeleteIssueAsync(createdIssue.Id);
                Assert.True(deleted, "The issue failed to delete via GraphQL mutation.");
                
                // Final Check
                try
                {
                    await _connector.GetIssueAsync(createdIssue.Id);
                    Assert.Fail("Issue should have been deleted, but GetIssueAsync succeeded.");
                }
                catch (Exception ex)
                {
                    Assert.Contains("410", ex.Message);
                }
            }
        }
    }

    [Fact]
    public async Task E2E_NativeWorkflowEngine_SimulatedProgression()
    {
        // 1. Create a dummy issue
        var testTitle = $"INT-TEST-FLOW: {Guid.NewGuid().ToString().Substring(0, 8)}";
        var createdIssue = await _connector.CreateIssueAsync(
            title: testTitle,
            body: "Testing full Native Workflow progression without LLMs.",
            type: "task",
            size: "1",
            project: "" // Bypass native triage
        );

        Assert.NotNull(createdIssue);
        var currentIssue = createdIssue;
        currentIssue.StepId = "open"; 
        currentIssue.Project = "requested";
        
        try
        {
            // Step 1a: open -> release-planning (Triage OK)
            currentIssue.StepId = "open";
            currentIssue.Project = "requested";
            var triage = Abo.Core.WorkflowEngine.GetTransitions(currentIssue.StepId)["triage_ok"];
            triage.ApplyState?.Invoke(currentIssue); // sets Project = "backlog"
            var updatedTriage = await _connector.UpdateIssueAsync(currentIssue.Id, project: currentIssue.Project, stepId: triage.NextStepId); // stepId = "release-planning"
            Assert.NotNull(updatedTriage);
            currentIssue.StepId = triage.NextStepId;
            await Task.Delay(2000);

            // Step 1b: release-planning -> planned (assign to next release)
            var t1 = Abo.Core.WorkflowEngine.GetTransitions(currentIssue.StepId)["assign_next"];
            t1.ApplyState?.Invoke(currentIssue); // sets Project = "release-next"
            var updated1 = await _connector.UpdateIssueAsync(currentIssue.Id, project: currentIssue.Project, stepId: t1.NextStepId);
            Assert.NotNull(updated1);
            currentIssue.StepId = t1.NextStepId; // now "planned"
            await Task.Delay(2000);

            var verify1 = await _connector.GetIssueAsync(currentIssue.Id);
            Assert.NotNull(verify1);
            // Assert.Equal("release-next", verify1.Project);
            Assert.Equal("planned", verify1.StepId);

            // Step 2: planned -> work
            var t2 = Abo.Core.WorkflowEngine.GetTransitions(currentIssue.StepId)["solution_planned"];
            t2.ApplyState?.Invoke(currentIssue); 
            var updated2 = await _connector.UpdateIssueAsync(currentIssue.Id, project: currentIssue.Project, stepId: t2.NextStepId);
            Assert.NotNull(updated2);
            currentIssue.StepId = t2.NextStepId; // now "work"
            await Task.Delay(2000);
            
            var verify2 = await _connector.GetIssueAsync(currentIssue.Id);
            Assert.NotNull(verify2);
            // Assert.Equal("release-next", verify2.Project);
            Assert.Equal("work", verify2.StepId);

            // Step 3: work -> review
            var t3 = Abo.Core.WorkflowEngine.GetTransitions(currentIssue.StepId)["implementation_completed"];
            t3.ApplyState?.Invoke(currentIssue);
            var updated3 = await _connector.UpdateIssueAsync(currentIssue.Id, project: currentIssue.Project, stepId: t3.NextStepId);
            Assert.NotNull(updated3);
            currentIssue.StepId = t3.NextStepId; // now "review"
            await Task.Delay(2000);
            
            var verify3 = await _connector.GetIssueAsync(currentIssue.Id);
            Assert.NotNull(verify3);
            // Assert.Equal("release-next", verify3.Project);
            Assert.Equal("review", verify3.StepId);

            // Step 4: review -> check
            var t4 = Abo.Core.WorkflowEngine.GetTransitions(currentIssue.StepId)["solution_accepted"];
            t4.ApplyState?.Invoke(currentIssue);
            var updated4 = await _connector.UpdateIssueAsync(currentIssue.Id, project: currentIssue.Project, stepId: t4.NextStepId);
            Assert.NotNull(updated4);
            currentIssue.StepId = t4.NextStepId; // now "check"
            await Task.Delay(2000);
            
            var verify4 = await _connector.GetIssueAsync(currentIssue.Id);
            Assert.NotNull(verify4);
            // Assert.Equal("release-next", verify4.Project);
            Assert.Equal("check", verify4.StepId);

            // Step 5: check -> done (AND explicitly close the issue RESTfully)
            var t5 = Abo.Core.WorkflowEngine.GetTransitions(currentIssue.StepId)["release_finished"];
            t5.ApplyState?.Invoke(currentIssue);
            var updated5 = await _connector.UpdateIssueAsync(currentIssue.Id, project: currentIssue.Project, stepId: t5.NextStepId, state: "closed");
            Assert.NotNull(updated5);
            currentIssue.StepId = t5.NextStepId; // now "done"
            await Task.Delay(2000);

            // Verify final closed state natively via REST
            var finalIssue = await _connector.GetIssueAsync(currentIssue.Id);
            Assert.NotNull(finalIssue);
            // Assert.Equal("release-next", finalIssue.Project);
            Assert.Equal("done", finalIssue.StepId);
            Assert.True(finalIssue.State.Equals("closed", StringComparison.OrdinalIgnoreCase), $"Issue should be closed, but was {finalIssue.State}");
        }
        finally
        {
            if (currentIssue != null && !string.IsNullOrWhiteSpace(currentIssue.Id))
            {
                await _connector.DeleteIssueAsync(currentIssue.Id);
            }
        }
    }
}
